// Built-in demo catalog used when Supabase is not configured.
const img = (label) =>
  `https://placehold.co/800x800/E7E2D6/8A8577?text=${encodeURIComponent(label)}`

export const MOCK_PRODUCTS = [
  { id: 'm1', name: 'Human Skull Anatomical Model', slug: 'human-skull-anatomical-model', price: 1200,
    description: 'Life-size 3D printed human skull with removable calvaria. Great for medical and dental students, or as a striking desk piece. Printed in durable PLA with a smooth matte finish.',
    category: 'bone-models', tags: ['skull', 'anatomy', 'medical', 'study', 'bone'],
    image_url: [img('Skull Model'), img('Skull Side'), img('Skull Base')], in_stock: true, created_at: '2026-06-10T10:00:00Z' },
  { id: 'm2', name: 'Human Heart Cross-Section Model', slug: 'human-heart-cross-section-model', price: 950,
    description: 'Detailed heart model showing chambers, valves and major vessels. Ideal for biology classrooms and clinics. Custom colours available on request.',
    category: 'bone-models', tags: ['heart', 'anatomy', 'medical', 'organ', 'study'],
    image_url: [img('Heart Model')], in_stock: true, created_at: '2026-06-12T10:00:00Z' },
  { id: 'm3', name: 'Vertebral Column Segment', slug: 'vertebral-column-segment', price: 800,
    description: 'Five-vertebra lumbar spine segment with intervertebral discs. Useful for physiotherapy demonstrations and anatomy revision.',
    category: 'bone-models', tags: ['spine', 'vertebra', 'anatomy', 'physio', 'bone'],
    image_url: [img('Spine Model')], in_stock: true, created_at: '2026-06-15T10:00:00Z' },
  { id: 'm4', name: 'Custom Name Keyring', slug: 'custom-name-keyring', price: 150,
    description: 'Personalised keyring with any name or short text in Bangla or English. Choose your colour. Perfect small gift or giveaway.',
    category: 'keyrings', tags: ['keyring', 'custom', 'name', 'gift', 'personalised'],
    image_url: [img('Name Keyring')], in_stock: true, created_at: '2026-06-18T10:00:00Z' },
  { id: 'm5', name: 'Logo Keyring (Bulk)', slug: 'logo-keyring-bulk', price: 120,
    description: 'Your business logo printed as a durable keyring. Bulk pricing for 25+ pieces — ideal for promotions and events. Contact us for a quote.',
    category: 'keyrings', tags: ['keyring', 'logo', 'business', 'bulk', 'promo'],
    image_url: [img('Logo Keyring')], in_stock: true, created_at: '2026-06-20T10:00:00Z' },
  { id: 'm6', name: 'Geometric Planter Pot', slug: 'geometric-planter-pot', price: 450,
    description: 'Low-poly geometric planter with drainage tray, for succulents and small plants. Available in several matte colours.',
    category: 'home-decor', tags: ['planter', 'pot', 'decor', 'plant', 'geometric'],
    image_url: [img('Planter Pot')], in_stock: true, created_at: '2026-06-22T10:00:00Z' },
  { id: 'm7', name: 'Spiral Table Lamp Shade', slug: 'spiral-table-lamp-shade', price: 700,
    description: 'Sculptural spiral lampshade that casts a warm patterned glow. Fits standard E27 bulb holders. A modern centrepiece for any room.',
    category: 'home-decor', tags: ['lamp', 'light', 'decor', 'spiral', 'home'],
    image_url: [img('Lamp Shade')], in_stock: true, created_at: '2026-06-25T10:00:00Z' },
  { id: 'm8', name: 'Personalised Photo Frame', slug: 'personalised-photo-frame', price: 350,
    description: 'Custom photo frame with a name or date printed into the border. A thoughtful gift for birthdays, weddings and anniversaries.',
    category: 'gifts', tags: ['frame', 'photo', 'gift', 'custom', 'personalised'],
    image_url: [img('Photo Frame')], in_stock: true, created_at: '2026-06-28T10:00:00Z' },
  { id: 'm9', name: 'Miniature Articulated Dragon', slug: 'miniature-articulated-dragon', price: 550,
    description: 'Fully articulated print-in-place dragon that bends and poses — no assembly needed. A fun fidget toy and desk companion.',
    category: 'gifts', tags: ['dragon', 'toy', 'articulated', 'fidget', 'gift'],
    image_url: [img('Dragon Toy')], in_stock: false, created_at: '2026-07-01T10:00:00Z' },
  { id: 'm10', name: 'Adjustable Phone Stand', slug: 'adjustable-phone-stand', price: 280,
    description: 'Foldable desk phone stand with adjustable viewing angle. Sturdy, lightweight and compact enough to carry in a bag.',
    category: 'miscellaneous', tags: ['phone', 'stand', 'desk', 'gadget', 'accessory'],
    image_url: [img('Phone Stand')], in_stock: true, created_at: '2026-07-03T10:00:00Z' },
  { id: 'm11', name: 'Cable Organizer Clips (Set of 6)', slug: 'cable-organizer-clips-set', price: 180,
    description: 'Set of six adhesive-backed cable clips to keep charging cables and cords tidy on your desk or bedside table.',
    category: 'miscellaneous', tags: ['cable', 'organizer', 'desk', 'clips', 'accessory'],
    image_url: [img('Cable Clips')], in_stock: true, created_at: '2026-07-05T10:00:00Z' },
  { id: 'm12', name: 'Pelvis Anatomical Model', slug: 'pelvis-anatomical-model', price: 1400,
    description: 'Life-size pelvic bone model with accurate landmarks for anatomy study and patient education. Custom scaling available.',
    category: 'bone-models', tags: ['pelvis', 'anatomy', 'bone', 'medical', 'study'],
    image_url: [img('Pelvis Model')], in_stock: true, created_at: '2026-07-07T10:00:00Z' },
]
